env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    #10
task:
    name: motoonepower
    timeout_in: 260m
    container:
        image: aarunalr/aosp-build
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config
      commands:
      - sudo apt-get install gpg
      - sudo apt-get update
      - sudo apt-get upgrade
    download_ccache_background_script: # To downloadw ccache in background
      - bash download_ccache # Ccache download script
    sync_script: # To sync rom source and dt, vt, kernel etc.
      - bash sync # Sync script
    build_script: # To build rom
      - bash build # Rom build script
    upload_ccache_script: # Upload ccache to clodud foreground
      - bash upload_ccache # Ccache uploading script
