env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    #10
task:
    name: motoonepower
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32g
      volumes:
          - /home/cirrus/ccache:/home/cirrus/ccache
      commands:
      - sudo apt-get install gpg
      - apt-get update
      - apt-get upgrade
    download_ccache_background_script: # To downloadw ccache in background
      - bash download_ccache # Ccache download script
    sync_script: # To sync rom source and dt, vt, kernel etc.
      - bash sync # Sync script
    build_script: # To build rom
      - bash build # Rom build script
    upload_ccache_script: # Upload ccache to clodud foreground
      - bash upload_ccache # Ccache uploading script
