#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

##some of my work
git config --global user.name "monu70152"
git config --global user.email "sunil9802506051@gmail.com"

# Repo init command
repo init -u ssh://git@github.com/DerpFest-12/manifest.git -b 12.1

# Local manifest
git clone https://github.com/monu70152/local_manifest.git --depth 1 -b arcana .repo/local_manifests

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
